.\" Manpage for filemanager
.\" Contact: Jefferson <jss.ssa@proton.me>
.\" Date: July 28, 2024
.\" 
.TH FILEMANAGER 1 "July 28, 2024" "Version 1.0" 
.SH NAME
C FIle Manager \- A terminal-based file manager written in C
.SH SYNOPSIS
.B filemanager
[\fIOPTIONS\fR]
.SH DESCRIPTION
.B CFL
is a terminal-based application for navigating and managing files in a UNIX-like file system environment. It provides functionality to browse directories, select files, execute operations on them, and manage bookmarks.

.SH OPTIONS
The following options are available when running
.B cfl:

.TP
.B \-h, \-\-help
Display this help message and exit.

.TP
.B \-v, \-\-version
Display version information and exit.

.SH USAGE
Run the application from the command line without any arguments to start in the current directory. Use the following keybindings to navigate and manage files:

.TP
.B k
Scroll up through the directory listing.

.TP
.B j
Scroll down through the directory listing.

.TP
.B KEY_NAVNEXT, \fBEnter\fR
Enter the selected directory or open the selected file.

.TP
.B h
Go back to the previous directory.

.TP
.B Shift + V
Select or deselect a file to copy/move.

.TP
.B p
Paste the previously selected files into the current directory.

.TP
.B !
Open a shell in the current directory.

.TP
.B Shift + R
Rename the selected file.

.TP
.B c
Empty the selection clipboard.

.TP
.B x
Open the removal menu for selected files.

.TP
.B =
Open the bookmarks menu.

.TP
.B +
Add a bookmark for the current directory.

.TP
.B -
Remove a bookmark.

.TP
.B KEY_VIEWSEL
View the list of selected files.

.TP
.B KEY_EDITSEL
Edit the list of selected files.

.TP
.B i
Show file information or preview.

.TP
.B .
Toggle the visibility of hidden files.

.TP
.B [
View a preview of the selected file.

.TP
.B #
Execute scripts on the selected files.

.SH ENVIRONMENT
.B filemanager
relies on the following environment variables:

.TP
.B EDITOR
Defines the text editor used for editing bookmarks and the selection list.

.TP
.B SHELL
Defines the shell to be used when opening a shell session.

.SH FILES
The following files are used by
.B filemanager:

.TP
.I ~/.config/cfl/bookmarks
The bookmark list file.

.TP
.I ~/.config/cfl/clipboard
The clipboard file for selected files.

.TP
.I Edit config.h
The configuration file for the file manager.

.SH BUGS
Please report issues to
.B <jeff.ssa@proton.me>.

.SH AUTHOR
Written by Jefferson Sa.

.SH COPYRIGHT
This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

