.\" Man page for cfl
.TH CFL 1 "August 2024" "Version 1.0" "User Commands"

.SH NAME
cfl \- A terminal-based file manager using ncurses.

.SH SYNOPSIS
.B cfl
.RI [ options ]
.RI [ directory ]

.SH DESCRIPTION
.B cfl
is a simple, terminal-based file manager written in C, utilizing the ncurses library to provide a user-friendly interface for browsing and managing files from the command line. It supports navigation, file operations, bookmarking, and previews.

.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Display help and exit.

.TP
\fB\-v\fR, \fB\-\-version\fR
Output version information and exit.

.TP
\fB<directory>\fR
Specify the directory to open on startup. If no directory is specified, the current working directory is used.

.SH KEY BINDINGS
The following key bindings are used for navigation and operations within the file manager:

.TP
\fBh\fR
Navigate to the parent directory.

.TP
\fBj\fR
Move the selection down.

.TP
\fBk\fR
Move the selection up.

.TP
\fBl\fR
Navigate to the selected directory or open the selected file.

.TP
\fBg\fR
Go to the beginning of the directory.

.TP
\fBG\fR
Go to the end of the directory.

.TP
\fBT\fR
Go to the top of the current view.

.TP
\fBM\fR
Go to the middle of the current view.

.TP
\fBB\fR
Go to the bottom of the current view.

.TP
\fB/\fR
Search all files with the current directory as base.

.TP
\fBs\fR
Search all files in the current directory.

.TP
\fBV\fR
Add files to the selection list.

.TP
\fB\t\fR (TAB)
View all the selected files.

.TP
\fBe\fR
Edit the clipboard file.

.TP
\fBc\fR
Empty the selection.

.TP
\fBp\fR
Copy files from the selection list to the current directory.

.TP
\fBm\fR
Move files from the selection list to the current directory.

.TP
\fBR\fR
Rename files in the selection list.

.TP
\fBd\fR
Open the remove menu for file deletion or moving to trash.

.TP
\fBg\fR
Move the file to the trash.

.TP
\fBd\fR
Delete the file permanently.

.TP
\fBi\fR
View file information.

.TP
\fB.\fR
Toggle the visibility of hidden files.

.TP
\fB=\fR
Open the bookmark list.

.TP
\fB+\fR
Add a bookmark for the current directory.

.TP
\fB-\fR
Remove a bookmark.

.TP
\fB#\fR
Open external scripts.

.TP
\fB!\fR
Open a shell in the current directory.

.TP
\fB[\fR
View the preview of the selected file.

.TP
\fBu\fR
Reload the current directory.

.TP
\fBq\fR
Quit the file manager.

.SH ENVIRONMENT VARIABLES
The following environment variables are used by
.B cfl:

.TP
.B SHELL
Specifies the shell to be used for executing commands. Default is \fB/bin/bash\fR if not set.

.TP
.B EDITOR
Specifies the editor to be used for editing files. Default is \fBnvim\fR if not set.

.TP
.B XDG_CONFIG_HOME
Specifies the base directory for user-specific configuration files. If not set, defaults to \fB$HOME/.config\fR.

.SH FILES
.B cfl
uses the following files for its operations:

.TP
\fB$XDG_CONFIG_HOME/cfl/bookmarks\fR
File containing user-defined bookmarks.

.TP
\fB$XDG_CONFIG_HOME/cfl/clipboard\fR
Temporary file used to store the clipboard content for file operations.

.TP
\fB$XDG_CONFIG_HOME/cfl/scripts\fR
Directory containing user-defined scripts.

.TP
\fB$HOME/.local/share/trash\fR
Directory used as a trash bin for files deleted from the file manager.

.SH EXAMPLES
Here are some examples of how to use
.B cfl:

.TP
.B cfl
Launch the file manager in the current directory.

.TP
.B cfl /path/to/directory
Open the specified directory on startup.

.TP
.B cfl \-h
Display help and usage information.

.TP
.B cfl \-v
Display the version information.

.SH AUTHOR
Written by Jeffeson Sá.
.br
Contact: \fBjeff.ssa@proton.me\fR
.br
Project repository: \fBhttp://github.com/vulto/cfl\fR

.SH BUGS
If you encounter any bugs or issues, please report them at the project repository:
.B http://github.com/vulto/cfl/issues

.SH COPYRIGHT
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 3 of the License, or (at your option) any later version.

.SH SEE ALSO
.B bash(1),
.B nvim(1),
.B ncurses(3)
